### ISSUE TITLE
Creating undirected graph

### ISSUE THREAD

**Issue by carissaynchen** [WangPeng-Lab/scGCO#4]
Hello,

I'm not sure what objects should be supplied to create the cellGraph variable. In the tutorial, if I understand correctly, the locs object should also contain the x-y coordinates, and only the first gene is supplied in the `exp` object -

`exp= data_norm.iloc[:,0]`
`cellGraph= create_graph_with_weight(locs, exp)`

Is the case for any dataset I supply?

Thank you!

**Comment by fengwanwan** [comment]
Hi,
Thanks for your interest in scGCO, you can create the cellGraph using the 2-D array locations (locs) and the same row length 1-D array exp.

**Comment by carissaynchen** [comment]
Hello, this error appears when I try to run CellGraph
